### ISSUE TITLE
gnome 42

### ISSUE THREAD

**Issue by Aur0nd** [kevinchappell/aws-default-profile-switcher#2]
would be lovely to see this maintained

**Comment by kevinchappell** [comment]
@Aur0nd thanks opening an issue, i was not aware there was a problem with gnome 42.

**Comment by kevinchappell** [comment]
@Aur0nd I'll be upgrading to 42 soon and be sure to make any changes to the extension if necessary

**Comment by kevinchappell** [comment]
@Aur0nd Thanks for reminding me to update this for newer versions of gnome. The updated version is now available: https://extensions.gnome.org/extension/4473/aws-default-profile-switcher/
